services:
  db:
    image: mysql:latest
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: nc_admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -e 'use nc_admin;' || exit 1"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
