ktor:
  application:
    modules:
      - com.neocampunism.ApplicationKt.module
  deployment:
    port: 8080
storageMySql:
  user: "root"
  password: ""
  schema: "nc_admin"
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://db:3306/nc_admin"
storageBaseX:
  user: "admin"
  password: "admin"
  db: "routine-v0.0.0"
  host: "localhost"
  port: 1984
jwt:
  secret: "secret"
  refreshSecret: "refreshSecret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/"
  realm: "admin service"
