ktor:
  application:
    modules:
      - com.neocampunism.ApplicationKt.module
  deployment:
    port: 8080
storage:
  type: "basex"
  user: "admin"
  password: "admin"
  schema: "nc_admin"
  host: "localhost"
  port: 1984
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
