ktor:
  application:
    modules:
      - com.neocampunism.ApplicationKt.module
  deployment:
    port: 8080
storage:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://db:3306/nc_admin"
  user: "root"
  password: ""
  schema: "nc_admin"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
