ktor:
  application:
    modules:
      - com.neocampunism.ApplicationKt.module
  deployment:
    port: 8080
storage:
  type: "mysql"
  user: "root"
  password: ""
  schema: "nc_admin"
  host: "db"
  port: 3306
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
